/**
 * Do not edit directly, this file was auto-generated.
 */

export const ColorVoid = "#231630"; // Page background. Always this or void-deep — never a light background (teamstep-landing-spec.md §2.1).
export const ColorVoidDeep = "#060610"; // Deepest background, used for the BBS Board section (teamstep-landing-spec.md §3).
export const ColorShadow = "#2d1e3e";
export const ColorMid = "#4f476d";
export const ColorMuted = "#7274a2";
export const ColorAccent = "#8591c9"; // Primary lilac.
export const ColorIce = "#e9f1f2"; // Near-white text.
export const ColorGreen = "#3c7a45"; // Meltdown / main-quest game-world accent. Scoped to its game-card context only.
export const ColorGreenHi = "#5cba6a";
export const ColorAmber = "#9a6a18"; // Coming-soon / in-dev accent.
export const ColorAmberHi = "#d4a830";
export const ColorBlood = "#6b2020"; // Witch One game-world accent. Scoped to its game-card context only.
export const ColorBloodHi = "#c94040";
export const ColorTeal = "#2a6070"; // UI chrome accent.
export const ColorTealHi = "#4a9baf";
export const ColorBackground = "#231630"; // Default page/section background.
export const ColorBackgroundRecessed = "#060610"; // Deepest background — BBS Board section only.
export const ColorSurface = "#2d1e3e"; // Raised panel/card surface over the page background.
export const ColorBorderDefault = "#4f476d";
export const ColorBorderEmphasis = "#8591c9";
export const ColorAccentPrimary = "#8591c9";
export const ColorTextPrimary = "#e9f1f2";
export const ColorTextSecondary = "#7274a2";
export const ColorTextTertiary = "#4f476d";
export const ColorGameGreen = "#3c7a45"; // Meltdown / main-quest scope only.
export const ColorGameGreenActive = "#5cba6a"; // Meltdown / main-quest scope only.
export const ColorGameBlood = "#6b2020"; // Witch One scope only.
export const ColorGameBloodActive = "#c94040"; // Witch One scope only.
export const ColorStatusPending = "#9a6a18"; // Coming-soon / in-development state.
export const ColorStatusPendingActive = "#d4a830";
export const ColorChromeAccent = "#2a6070"; // UI chrome (non-game, non-status) accent.
export const ColorChromeAccentActive = "#4a9baf";
export const Spacing100 = "8px";
export const Spacing150 = "12px";
export const Spacing200 = "16px";
export const Spacing300 = "20px";
export const Spacing400 = "24px";
export const Spacing600 = "32px";
export const Spacing800 = "40px";
export const Spacing1000 = "48px";
export const Spacing1200 = "64px";
export const Spacing1600 = "96px";
export const Spacing050 = "4px";
export const SpacingXs = "4px";
export const SpacingSm = "8px";
export const SpacingMd = "16px";
export const SpacingLg = "24px";
export const SpacingXl = "32px";
export const Spacing2xl = "40px";
export const Spacing3xl = "64px";
export const SpacingSection = "96px";
export const Radius100 = "4px";
export const Radius150 = "5px";
export const Radius200 = "6px";
export const Radius300 = "8px";
export const Radius400 = "10px";
export const Radius500 = "12px";
export const Radius600 = "16px";
export const RadiusHairline = "1px"; // Sharp-corner value for the chip/CTA-scale asymmetric radius pattern.
export const RadiusTight = "2px"; // Sharp-corner value for the card-scale asymmetric radius pattern.
export const RadiusChipSm = "1px 4px 1px 4px"; // Asymmetric top-left/bottom-right radius for small chips (badges).
export const RadiusChipMd = "1px 5px 1px 5px"; // Asymmetric radius for ghost CTAs.
export const RadiusChipLg = "1px 6px 1px 6px"; // Asymmetric radius for primary/secondary CTAs.
export const RadiusCardSm = "2px 8px 2px 8px"; // Asymmetric radius for archive cards, service cards.
export const RadiusCardMd = "2px 10px 2px 10px"; // Asymmetric radius for dialogue boxes.
export const RadiusCardLg = "2px 12px 2px 12px"; // Asymmetric radius for the featured game card.
export const FontFamilyRajdhani = "Rajdhani, sans-serif"; // Web equivalent for the Carbon brand font. Headings / wordmark, uppercase only.
export const FontFamilyNunito = "Nunito, sans-serif"; // Web equivalent for the Acumin brand font. Subtitles / italic accent.
export const FontFamilyBarlowCondensed = "Barlow Condensed, sans-serif"; // Web equivalent for the Bahnschrift brand font. Body / UI text.
export const FontFamilyHeading = "Rajdhani, sans-serif"; // Section titles, hero H1, wordmark. Apply uppercase in component CSS.
export const FontFamilySubtitle = "Nunito, sans-serif"; // Taglines, secondary labels. Apply italic in component CSS.
export const FontFamilyBody = "Barlow Condensed, sans-serif"; // Body copy, BBS feed, badges.
